//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant1.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
