//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant1.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statements
    {
        public int ID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public string Description { get; set; }
    
        public virtual Activities Activities { get; set; }
    }
}
